---
apiVersion: v1
kind: Pod
metadata:
  name: mynewpod
spec:
  containers:
  - name: my-web-container
    image: submar1n3/webimage:v6
    resources:
      requests:
        memory: "512Mi"
        cpu: 0.5

