---
apiVersion: v1
kind: Pod
metadata:
  name: mytestpod
spec: 
  containers:
  - name: frontend-con
    image: submar1n3/webimage:v6
  tolerations:
  - key: "env"
    operator: "Equal"    
    value: "test"
    effect: "NoSchedule"
