apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command - ["sleep"]
    args - ["3600"]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always